- OSC.md
> Document signature of the OSC messages

- CONTRIBUTING.md
- mpop_dataviz/main.cpp
Change the default window width so that the ratio is 7:6, not 16:9.
Closes #67
> Change default window width

- scripts/sh_send_osc_show_one_answer_by_gender.sh
> Fix the OSC message sent for one answer by gender

- Mpop.pro
- mpop_service/main.cpp
- mpop_service/mpop_service.pro
- mpop_service/mpopservice.cpp
- mpop_service/mpopservice.h
- test_mpop_service/TestMpopService.cpp
- test_mpop_service/TestMpopService.h
- test_mpop_service/main.cpp
- test_mpop_service/test_mpop_service.pro
If it's not possible to connect to the database, the test run will fail. Run the tests from Qt Creator, just like it's a Qt application.
> Add some integration tests for the mpop_service and its facade

- mpop_kiosk/mpop_kiosk.pro
Kiosk should now link to the OpenGL libraries.
Closes #184 184
> Link kiosk to OpenGL

- mpop_kiosk/DatavizManager.qml
- mpop_kiosk/ModelGenders.qml
- mpop_kiosk/PageAge.qml
- mpop_kiosk/PageEthnicity.qml
- mpop_kiosk/PageFinalQuestion.qml
- mpop_kiosk/PageSingleQuestion.qml
- mpop_kiosk/WidgetAgeSlider.qml
- mpop_kiosk/WidgetAnswerSlider.qml
- mpop_kiosk/WidgetChoiceButton.qml
- mpop_kiosk/WidgetPreviousNext.qml
- mpop_kiosk/WidgetQuestionButton.qml
- mpop_kiosk/main.cpp
- mpop_kiosk/main.qml
- mpop_kiosk/mpop_kiosk.pro
- mpop_kiosk/qml.qrc
Set up the general layout for the kiosk.
> General layout for the kiosk

- mpop_service/facade.cpp
- mpop_service/facade.h
- mpop_service/mpopservice.cpp
- test_mpop_service/TestMpopService.cpp
> Implement RPC-SQL methods in facade

- Dockerfile
- docker-compose.yml
- mpop_service/facade.cpp
- mpop_service/mpopservice.cpp
- run-test.sh
Circumvents QMYSQL driver not loaded #193
> Fix service build within docker

- mpop_service/facade.cpp
- run-test.sh
- test_mpop_service/TestMpopService.cpp
- test_mpop_service/TestMpopService.h
> fix bug for create user or tag for duplicate entry and implement unit test

- .gitignore
- INSTALL.md
- mpop_kiosk/kioskconfig.h
- mpop_kiosk/main.cpp
- mpop_kiosk/main.qml
Document the env vars for kiosk.
Closes #6
> (kiosk) Parse the kiosk_mode and is_fullscreen env vars

- mpop_kiosk/languageswitcher.cpp
- mpop_kiosk/mpop_kiosk.pro
- mpop_kiosk/qml.qrc
This is an attempt to fix the dynamic translations.
It's not quite effective, yet.
Part of #219
> Use QRC resource system for the translation files

- mpop_kiosk/UserProfile.qml
- mpop_service/facade.cpp
- mpop_service/missingparametererror.h
- mpop_service/mpop_service.pro
- mpop_service/mpopservice.cpp
- mpop_service/request.cpp
- mpop_service/request.h
- mpop_service/response.cpp
- test_mpop_service/TestMpopService.cpp
- test_mpop_service/TestMpopService.h
> using try catch block for RPC methods

- mpop_kiosk/main.qml
- mpop_service/facade.cpp
- mpop_service/facade.h
- mpop_service/mpopservice.cpp
- mpop_service/request.cpp
- mpop_service/request.h
- mpop_service/response.cpp
- mpop_service/response.h
- test_mpop_service/TestMpopService.cpp
- test_mpop_service/TestMpopService.h
Skip some unit tests if there is no MySQL connection
Closes #223
> Fix ID field in JSON-RPC requests and responses

- CONTRIBUTING.md
- flyway/sql/V1__create_tables.sql
- flyway/sql/V2__insert_nations_and_questions.sql
- mpop_kiosk/ModelGenders.qml
- mpop_kiosk/ModelNations.qml
- mpop_kiosk/ModelPageButtons.qml
- mpop_kiosk/PageEthnicity.qml
- mpop_kiosk/PageGender.qml
- mpop_kiosk/UserProfile.qml
- mpop_kiosk/WidgetChoiceButton.qml
- mpop_kiosk/WidgetPreviousNext.qml
- mpop_kiosk/WidgetQuestionButton.qml
- mpop_kiosk/main.qml
- mpop_kiosk/qml.qrc
- mpop_service/facade.cpp
- mpop_service/facade.h
- mpop_service/mpopservice.cpp
- mpop_service/mpopservice.h
- mpop_service/response.cpp
- scripts/sh_run_service.sh
- scripts/sh_test_mpop_service.sh
- test_mpop_service/TestMpopService.cpp
- test_mpop_service/TestMpopService.h
- Add setUserAge
- Call setUserLanguage/Ethnicity/Gender/Age
- Call getUserAnswers
- Test the errors in responses from the service
- Improve unit tests for the service
- Retrieve user info
- Progress in implementing the requests and responses
- Highlight current page button
- Add more documentation
Part of #176 
Make sure to reset your database, once you've checked out this version:
```
docker-compose down --volumes
```
> Implement more RPC calls

- docker-compose.yml
> PhpMyAdmin now automatically connects to the DB

- mpop_kiosk/PageMultipleQuestion.qml
- mpop_kiosk/PageSingleQuestion.qml
- mpop_kiosk/WidgetAnswerSlider.qml
- mpop_kiosk/WidgetPreviousNext.qml
- mpop_kiosk/main.qml
> layout for the single question

- mpop_service/facade.cpp
- mpop_service/facade.h
- mpop_service/mpopservice.cpp
- test_mpop_service/TestMpopService.cpp
- test_mpop_service/TestMpopService.h
> Implement Get User Ans Avg, Json Rpc Handler, Unit Test, Fix UserInfo Method for Null Ethnicity , Fix Unit Test for GetLang, GetGender and GetEthn

- mpop_kiosk/screensaver.cpp
- mpop_kiosk/screensaver.h
Hi, I'm not able to test it on an high DPI screen but I'm pretty sure it is fix
> attempt to fix the issues #192

- mpop_kiosk/ModelQuestions.qml
- mpop_kiosk/PageMultipleQuestion.qml
- mpop_kiosk/PageSingleQuestion.qml
- mpop_kiosk/WidgetAnswerSlider.qml
- mpop_kiosk/main.qml
> multiple question page layout

- mpop_service/mpopservice.cpp
> implement RPC-Methods for GetAns*

- mpop_kiosk/DatavizManager.qml
- mpop_kiosk/main.qml
> The DatavizManager can send OSC to mpop_dataviz

- mpop_kiosk/DatavizManager.qml
Done with implement OSC senders
> Finalize the DatavizManager

- CONTRIBUTING.md
- INSTALL.md
- README.md
- mpop_kiosk/DatavizManager.qml
- mpop_kiosk/PageEntrance.qml
- mpop_kiosk/PageQuestion.qml
- mpop_kiosk/UserProfile.qml
- mpop_kiosk/WidgetAgeRangeSlider.qml
- mpop_kiosk/WidgetAnswerSlider.qml
- mpop_kiosk/main.cpp
- mpop_kiosk/main.qml
- mpop_kiosk/qml.qrc
Parse the command-line options in the kiosk and show every question page.
> Feature complete questions

- mpop_kiosk/main.qml
> Message and thank you page

- CONTRIBUTING.md
> Documented Dataviz run on Windows machine

- mpop_service/config.h
- mpop_service/facade.cpp
- mpop_service/facade.h
- mpop_service/main.cpp
- mpop_service/mpopservice.cpp
- mpop_service/mpopservice.h
close #308 , #204
Implement "timeWatcher" Function, Call freeAllTag when the current system time reaches to the mid Night 00:01.
Used Config Var periodic Interval of 1 min.
> Implement QTimer for FreeAll Tag

- flyway/sql/V1__create_tables.sql
- mpop_service/facade.cpp
- mpop_service/mpop_service.pro
- mpop_service/mpopservice.cpp
- mpop_service/sqlerror.h
- test_mpop_service/TestMpopService.cpp
> Exception handling services

- mpop_kiosk/PageQuestion.qml
- mpop_kiosk/WidgetAgeRangeSlider.qml
- mpop_kiosk/WidgetAnswerSlider.qml
- mpop_kiosk/WidgetFilterButton.qml
- mpop_kiosk/WidgetPreviousNext.qml
- mpop_kiosk/main.qml
also defined and propagated `invertedTheme` property, which switches between both light/dark color themes depending on state of application.
> Fix some layout bugs in PageQuestion

- mpop_kiosk/PageEntrance.qml
- mpop_kiosk/PageFinalQuestion.qml
- mpop_kiosk/main.qml
closes #336 
window width/height properties have also been slightly tweaked to be remapped to 1024x640 only when `kioskConfig.kiosk_mode` equals to `entrance` or `exit`, in order to conform to mockups.
> Update layout for kiosk exit mode

- scripts/sh_rm_volumes_build_and_test.sh
> Add scripts/sh_rm_volumes_build_and_test.sh

- mpop_kiosk/WidgetAgeRangeSlider.qml
- mpop_kiosk/WidgetAnswerSlider.qml
- mpop_kiosk/WidgetChoiceButton.qml
- mpop_kiosk/WidgetFilterButton.qml
- mpop_kiosk/WidgetGoToDataviz.qml
- mpop_kiosk/WidgetIconButton.qml
- mpop_kiosk/WidgetQuestionButton.qml
- mpop_kiosk/main.qml
I've attempted to fix the idleTimer, and the way it works, but it's not working.
EDIT 2020-09-11: it now works.
closes #188
> Go to screensaver when application is idle for 2 minutes

- mpop_kiosk/PageEntrance.qml
- mpop_kiosk/PageQuestion.qml
- mpop_kiosk/UserProfile.qml
- mpop_kiosk/WidgetAgeRangeSlider.qml
- mpop_kiosk/main.qml
- Fixes loading the answers
- Fixes the build with Qt 5.7
- Closes #99
> Fix loading answers

- mpop_kiosk/UserProfile.qml
- mpop_kiosk/main.qml
closing #358 
checked kiosk mode after populate user info calls back function.  instead of UserId change Event.
> Fix bug for Skip demographic Que if already answred

- mpop_kiosk/UserProfile.qml
- mpop_kiosk/main.qml
- test_mpop_kiosk/tst_mpop_kiosk.qml
- Fix a bug: setUserAnswer changes the user's age
> Add a system test that sets some answers and answers the demographic questions

- mpop_kiosk/PageQuestion.qml
- mpop_kiosk/UserProfile.qml
- mpop_service/facade.cpp
- mpop_service/facade.h
- mpop_service/mpopservice.cpp
implement kiosk get Answer method
> Kiosk get answers

- mpop_service/facade.cpp
- mpop_service/mpopservice.cpp
- test_mpop_kiosk/tst_mpop_kiosk.qml
> Improve logging, fix coding style and uncomment commented system tests

- mpop_kiosk/PageQuestion.qml
- mpop_kiosk/UserProfile.qml
- mpop_service/mpopservice.cpp
- mpop_service/mpopservice.h
> Fix Bug for Get Ans By age and get Answers

- mpop_kiosk/mpop_kiosk.pro
- mpop_kiosk/rfidreader.cpp
- mpop_kiosk/rfidreader.h
So that it builds within Docker
> Fix a path in mpop_kiosk.pro

- mpop_dataviz/controller.cpp
- mpop_kiosk/DatavizManager.qml
- mpop_kiosk/PageQuestion.qml
> Osc message fun

- mpop_service/missingparametererror.h
- mpop_service/sqlerror.h
> Fix exception handling

- mpop_kiosk/UserProfile.qml
- mpop_kiosk/main.qml
> Fix callback id remove on user ideal

- .gitignore
- CONTRIBUTING.md
- INSTALL.md
- mpop_kiosk/main.cpp
- mpop_kiosk/main.qml
The OSC send options are now:
- --dataviz-host
- --dataviz-port
> Remove OSC receiver in the kiosk and simplify CLI options

- mpop_kiosk/PageQuestion.qml
close #445 
please try it out.. I'm unable to run DataViz.. tried different setting to connect with another computer over wifi, but no luck
> Fix Multiple Que display

- mpop_service/facade.cpp
- mpop_service/facade.h
- scripts/sh_test_mpop_service.sh
> Fix date filter

- mpop_kiosk/DatavizManager.qml
- mpop_kiosk/PageQuestion.qml
- mpop_kiosk/main.qml
- scripts/ssh-config
Closes #446
Probably also #459
> Stay in the same tab in every question page

- mpop_kiosk/main.qml
> Hide "You can now" page after 5 seconds

- mpop_dataviz/controller.cpp
- mpop_kiosk/DatavizManager.qml
- mpop_kiosk/PageQuestion.qml
> Fix the OSC method /my_answers

- mpop_dataviz/main.cpp
Closes #480
Fine-tune the adjustment
> Add a margin in the center

- qosc/oscreceiver.cpp
- scripts/lunch_kiosk.py
- scripts/sh_left.sh
- scripts/sh_right.sh
Also run dataviz within a shell script
> Remove one more print - it was crashing the dataviz

- mpop_kiosk/DatavizManager.qml
- mpop_kiosk/ModelQuestions.qml
- mpop_kiosk/PageQuestion.qml
- mpop_kiosk/UserProfile.qml
- mpop_kiosk/main.qml
- qosc/oscsender.cpp
> Fix view answers

- mpop_kiosk/PageFinalQuestion.qml
- mpop_kiosk/UserProfile.qml
- mpop_kiosk/main.qml
> Free tag when Screen Saver comes or new Tag scans 
